### ISSUE TITLE
Bug - Anchor prompt/handling on signing tx

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#390]
**Description**
Anchor in chrome iOS prompts with the “launch anchor” tab and after signing returns to a 2nd new “launch anchor” tab.

**Desired Solution**
- dismiss and return to app on success 
- display error on failure 
- not open duplicate 'launch' tab

**Additional Context**
feedback via @poplexity

**Comment by Kersten-TCD** [comment]
@donnyquixotic @karynemayer I can not recreate the issue on my iPhone, seems to work fine.

- Login to explorer.telos.net only prompts Anchor once and returns to browser once signing is approved.
- Test transaction unstake from REX works as expected, Anchor sign request opens app as expected and returns to Chrome after signature
- Send function works as expected, too

- If signature request in Anchor is cancelled, I am not returned to the browser though, is this an expected behavior?

iOS Version:16.0.2
Chrome Version: 107.0.5304.66
Safari Version: latest
