### ISSUE TITLE
Chain icon improvements

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#440]
## Overview

The icons on the chain switcher don't look proportional. There is also space for improvements on the experience, like adding a testnet tag to the icons when using testnet.

<img width="156" alt="Screen Shot 2022-11-10 at 22 14 54" src="https://user-images.githubusercontent.com/2939354/201275744-3f3ab22b-0cca-4946-a6ea-02248b7d88e3.png">

## Acceptance criteria

- All logos (both on language switcher and the header) must look proportional
- All logos for testnet chains should contain a testnet tag/mark
- The chains should be in alphabetical order
- There must be a clear indication on the chain switcher for the chain that is selected. (e.g. different background color)

**Comment by donnyquixotic** [comment]
@karynemayer 
- the logos are rendered with the same fixed height/width, the asymmetry and different shape(s) may make them look disproportionate, we could possibly resize or style the source images (located in `public/chains`)
- yea, we could do that, right now the testnets are seperated by the divider bar
- there was a decision to list them alphabetically under the assumption we would eventually introduce this for Antelope-wide use as an agnostic/fair way to list them

**Comment by karynemayer** [comment]
@Kersten-TCD what do you think about the list?

**Comment by Kersten-TCD** [comment]
@karynemayer @donnyquixotic for items 1+2 I am fine.

For item 3, this is a valid comment since the initial chain displayed is Telos when opening explorer.telos.net this should be ok, while it might be confusing to some users.

We could sort this dynamically based on URL, so for explorer.telos.net we could move the Telos logo to the top with a divider bar and have the other chains listed alphabetically below. Same could apply if anyone used explorer.chain.xyz. In case this would be use on explorer.Antelope.io a strict alphabetical order without divider bar would be mandatory.

**Comment by karynemayer** [comment]
@Kersten-TCD @donnyquixotic If the problem is indicating which of the chains is active, I would suggest we highlight the one that is active with a different background on the chain selector.

Changing the order of the menu would require the user to search ( re-learn) where other chains are every time they change it. By keeping the same approach, the user can memorize the placement of used chains and not have to think about where to click.

**Comment by Kersten-TCD** [comment]
@karynemayer very good point, I agree
