### ISSUE TITLE
Execute MSIG tx by non MSIG Accounts on Block Explorer

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/open-block-explorer#835]
On MSIG tx, allow any account to execute it, currently only MSIG accounts can it seems.

Refinement:
The problem is that the condition isApproved is currently calculated wrong.

Let's call this first case a private proposal in which only private accounts are part of the requested approvals. In this case the `isApproved `property should be taking into account the amount of requested versus approved and they have to be the same.
http://localhost:8080/proposal/voqbcbtcll3j
![image](https://github.com/telosnetwork/open-block-explorer/assets/4420760/78746bef-ebcb-42dc-b840-ab554cead78f)

Let's call this other case a public proposal where the approval of BPs where solicited. In this other different case, we need at least (2/3+1) of the total amount of active BPs having approved the proposal. Only in that case, the proposal is approved.
http://localhost:8080/proposal/aprfeeburn
![image](https://github.com/telosnetwork/open-block-explorer/assets/4420760/b9872833-94d0-4bd5-971a-cfac93730eb0)

**Comment by rozzaswap** [comment]
May already be resolved by https://github.com/telosnetwork/open-block-explorer/pull/829

**Comment by Viterbo** [comment]
I'm reopening this issue because it seems not to work on production.

**Comment by Viterbo** [comment]
This issue is solved.
You can see in this already-approved proposal that the execute buttons appear even when I'm logged in with an account that has not participated from the miiltisig. however, you need to be logged to see the button.

https://explorer-test.telos.net/proposal/axlspauos13o

![image](https://github.com/telosnetwork/open-block-explorer/assets/4420760/7e8121fa-1ae5-4b0c-a9c2-2bbe6b1362fa)
